### ISSUE TITLE
Typo causes infinite loop

### ISSUE THREAD

**Issue by Kuldaen** [andrewwillmott/splines-lib#1]
I found a little typo which causes an infinitely look when I do interesections of 3D splines that are on the z-plane. (eg Z=0)

https://github.com/andrewwillmott/splines-lib/blob/9c56e32d34cc796fd293e541f22f117e9e7b825f/Splines.cpp#L76

The check should be ` d.z > t;`

**Comment by andrewwillmott** [comment]
Fixed, thanks!
